/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "accuracyText": "floating point accuracy",
    "accuracyText1": "clipboard accuracy:",
    "accuracyText2": "RGB format",
    "accuracyText3": "HSV format",
    "accuracyText4": "floating point accuracy",
    "cancel": "cancel",
    "cancelButton": "cancel",
    "copyright": "©2012 John Einselen, Vectorform LLC",
    "createButton": "create",
    "createText": "does not exist",
    "doneButton": "done",
    "downloadButton": "download",
    "explanation": "To sync multiple computers via Dropbox, use ~/Dropbox/ and the desired subfolder.\nRemote changes may not show up until you add, remove, or refresh by clicking \"done.\"",
    "explanationText": "To sync multiple computers via Dropbox, use ~/Dropbox/ and the desired subfolder.\nRemote changes may not show up until you add, remove, or refresh by clicking \"done.\"",
    "failRepeat": "if you see this message more than once, please restart the Dashboard",
    "failText": "library processing\nalready in progress",
    "formatHSVText": "HSV format",
    "formatRGBText": "RGB format",
    "iaian7com": "For more information, please visit iaian7.com/dashboard/chroma",
    "libraryExportSuccess": "ok",
    "libraryExportSuccessText": "library data succesfully written to clipboard.",
    "libraryExportText": "library data succesfully written to clipboard.",
    "libraryFailText": "sorry, no library data found in the clipboard.",
    "libraryImportAdd": "add to data",
    "libraryImportAdd1": "add to data",
    "libraryImportCancel": "cancel",
    "libraryImportFail": "start over",
    "libraryImportFailText": "sorry, no library data found in the clipboard.",
    "libraryImportReplace": "replace data",
    "libraryImportSuccess": "ok",
    "libraryImportSuccessText": "library processing successful.",
    "libraryImportText": "import succeeded, how should data be used?",
    "libraryInputFail": "sorry, no library data found in the clipboard.",
    "libraryMenuExport": "export",
    "libraryMenuImport": "import",
    "libraryMenuText": "exchange library data via the OSX clipboard:",
    "libraryMenuTryAgain": "start over",
    "librarySuccessFinished": "awesome",
    "librarySuccessText": "library processing successful.",
    "locationText": "clipboard accuracy:",
    "mustContain": "group and name fields must\ncontain at least one character each",
    "newText": "new update available!",
    "newVersion": "version number\nversion description",
    "preferenceText": "floating point values will be displayed with only two decimals of accuracy, but will be copied to the clipboard using the selected accuracy level.\n\nswatches will always include full precision values when saved to the library, so no colour data is ever lost, and conversions are reliable.",
    "saveSwatch": "save to library",
    "settingsButton": "settings",
    "setupButton": "cancel",
    "skipButton": "skip version",
    "sortText": "library settings",
    "sortText1": "swatch display:",
    "successText": "library creation successful",
    "textHEX\nE\nX": "H\nE\nX",
    "textHSV\nS\nV": "H\nS\nV",
    "textRGB\nG\nB": "R\nG\nB",
    "truncatedText": "library input truncated,\ncorruption prevented",
    "tryButton": "try again"
};









