/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "add": "+",
    "cancelButton": "cancel",
    "cancelSwatch": "x",
    "createButton": "create",
    "createText": "\ndoes not exist",
    "doneButton": "done",
    "downloadButton": "download",
    "explanation": "To sync multiple computers via Dropbox, use ~/Dropbox/ and the desired subfolder.\nRemote changes may not show up until you add, remove, or refresh by clicking \"done.\"",
    "explanationText": "To sync multiple computers via Dropbox, use ~/Dropbox/ and the desired subfolder.\nRemote changes may not show up until you add, remove, or refresh by clicking \"done.\"",
    "failText": "library processing\nalready in progress",
    "iaian7com": "For more information, please visit iaian7.com/dashboard/chroma",
    "ItemColor": "255 255 255",
    "ItemHex": "#FFFFFF",
    "ItemHEX": "#FF8C19",
    "ItemHSV": "30 90 100",
    "ItemRGB": "255 140 25",
    "locationText": "library location",
    "mustContain": "group and name must\ncontain at least one letter",
    "newText": "new update available!",
    "newVersion": "version number\nversion description",
    "saveSwatch": "save to library",
    "settingsButton": "settings",
    "setupButton": "cancel",
    "skipButton": "skip version",
    "successText": "library creation successful",
    "textHEX\nE\nX": "H\nE\nX",
    "textHSV\nS\nV": "H\nS\nV",
    "textRGB\nG\nB": "R\nG\nB",
    "truncatedText": "library input truncated,\ncorruption prevented",
    "tryButton": "try again"
};
