/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "add": "+",
    "Brgb": "b",
    "done": "done",
    "download": "download",
    "drop": "drop MOHO file here",
    "explanation": "Custom phoneme lists should be comma delimited and contain no spaces.",
    "fail": "file conversion failed\nplease try again",
    "Grgb": "g",
    "iaian7com": "For more information, please visit iaian7.com/dashboard/chroma",
    "locationText": "library location",
    "new": "new update available!",
    "newVersion": "version number\nversion description",
    "preset1": "user preset 1",
    "preset2": "preference location",
    "Rrgb": "r",
    "Rrgb1": "r",
    "Rrgb2": "r",
    "skip": "skip version",
    "success": "file conversion\nwas successful",
    "success2": "(envelope files saved)",
    "successAE": "file conversion\nwas successful\n(and copied to clipboard)",
    "successAE2": "sequential phoneme list:",
    "successAEoutput": "sequential phoneme list",
    "textHEX\nE\nX": "H\nE\nX",
    "textHSV\nS\nV": "H\nS\nV",
    "textRGB\nG\nB": "R\nG\nB",
    "textRGB\nG\nB1": "R\nG\nB",
    "wrong": "wrong file format\nplease try again"
};
