/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "add": { "creationFunction": "CreateShape" },
    "doneSave": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showFront", "rightImageWidth": 5, "text": "done" },
    "download": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "versionDownload", "rightImageWidth": 5, "text": "download" },
    "explanation": { "creationFunction": "CreateText", "text": "explanation" },
    "failButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done" },
    "failText": { "creationFunction": "CreateText", "text": "fail" },
    "iaian7com": { "creationFunction": "CreateText", "text": "iaian7com" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "locationText": { "creationFunction": "CreateText", "text": "locationText" },
    "new": { "creationFunction": "CreateText", "text": "new" },
    "newVersion": { "creationFunction": "CreateText", "text": "newVersion" },
    "skip": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "skip" },
    "sort": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "name": "sort", "onchange": "updatePhoneme", "options": [["sort by name", "name"], ["sort by hue", "hue"], ["sort by saturation", "saturation"], ["sort by value", "value"]], "rightImageWidth": 16 },
    "stack": { "creationFunction": "CreateStackLayout", "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }] },
    "stack2": { "creationFunction": "CreateStackLayout", "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }] },
    "successButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done" },
    "successText": { "creationFunction": "CreateText", "text": "success" },
    "successText2": { "creationFunction": "CreateText", "text": "success2" },
    "swatch": { "creationFunction": "CreateShape", "leftImageWidth": 5, "rightImageWidth": 5 },
    "text": { "creationFunction": "CreateText", "text": "©2009 John Einselen / Vectorform LLC" },
    "textHEX": { "creationFunction": "CreateText", "text": "textHEX\nE\nX" },
    "textHSV": { "creationFunction": "CreateText", "text": "textHSV\nS\nV" },
    "textRGB": { "creationFunction": "CreateText", "text": "textRGB\nG\nB" },
    "wrongButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done" },
    "wrongText": { "creationFunction": "CreateText", "text": "wrong" }
};
